### PR TITLE
Allow for latest hackney in dependencies

### PR DESCRIPTION
**Pull request by Zurga**
I changed the hackney dependency to allow for a newer version to be used. All tests passed for me.

### CODE REVIEW

**Comment by dallagi** [comment]
Hi @Zurga , thanks for the PR!
I agree with the idea of allowing more recent versions of hackney.
Would you mind changing the version requirement from `> 1.16.0` to `~> 1.16`?
This way it would still allow for newer minor versions of hackney to be used, but it would also protect against new major versions with potential breaking changes.

Thank you!

**Comment by Zurga** [comment]
Hey @dallagi,

Yes you are right, this is a bit too broad. I will change it tomorrow.

Love the library! Really nice for spinning up containers to do mock testing.

**Comment by Zurga** [comment]
It should be good now.

**Comment by dallagi** [comment]
Awesome, thank you 😄

**Pull request merged**
